version: "3.6"

services:
 
  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:$TRAEFIK_TAG
    container_name: "${PROJECT_NAME}_traefik"
    # @TODO: https!
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # https://stackoverflow.com/questions/48851190/docker-compose-override-a-ports-property-instead-of-merging-it
    ports:
     - '8000:80'
     - '8444:443'
